spring:
  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority
      database: schooldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nishant16405@gmail.com
    password: **** **** **** ****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /school
